name = "quantumdynamics"
uuid = "5e446358-0066-4a90-8799-3c098b56d9fd"
authors = ["ajstaat <alst0620@colorado.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
